name: ✨ Daily Quote Updater  

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-quote:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.MY_PAT_TOKEN }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install Python Dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt, skipping..."

      - name: 🚀 Run quote.py Script
        run: python quote.py

      - name: 📤 Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "📝 updated quote for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git remote set-url origin https://shamkumar06:${TOKEN}@github.com/shamkumar06/Shamkumar06.git
          git push
