# .github/workflows/quote.yml

name: ✨ Update Daily Quote

on:
  schedule:
    - cron: '0 4 * * *' # Every day at 9:30 AM IST
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 🚀 Run quote script
        run: python scripts/quote.py

      - name: 🔐 Commit & Push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "🔁 update: Daily quote"
          git push
