name: 🧠 Update README with Quote

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout Repository
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: pip install requests

    - name: 🧾 Run Python script
      run: python scripts/quote.py

    - name: ✅ Commit and Push changes
      env:
        TOKEN: ${{ secrets.MY_PAT_TOKEN }}
      run: |
        git config --global user.name 'shamkumar06'
        git config --global user.email 'you@example.com'
        git add README.md
        git diff --cached --quiet || git commit -m "🔁 Update Quote of the Day"
        git remote set-url origin https://shamkumar06:${TOKEN}@github.com/shamkumar06/Shamkumar06.git
        git push origin main
