name: 🔁 Update Quote of the Day

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:
  
permissions:
  contents: write


jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate random quote
        id: quote
        run: |
          quotes=(“Arise.”  
          “I am not weak anymore.”  
          “I want to live. No, I will live.”  
          “One by one, I’ll prove it. That I can do it.”  
          “If you can’t avoid it, then you might as well enjoy it.”  
          “Even in a world where only the strong survive, I will become the strongest.”  
          “It’s not that I want to win. I just don’t want to lose.”  
          “The system… is both a blessing and a curse.”  
          “No one else needs to die.”  
          “There’s no turning back now.”  
          “I have to become stronger. For myself, for my family.”  
          “They called me the weakest hunter, but none of them can look down on me now.”  
          “No price is too high for my family’s safety.”  
          “I am not the person I once was.”  
          “This power… I will use it to protect the things I care about.”  
          “This is not a miracle. It’s hard work.”  
          “Don’t blame the system. Blame your own weakness.”  
          “Today, I become someone who hunts the hunters.”  
          “No one else needs to know what I’ve gone through.”  
          “From now on, I decide my own fate.”  
          “You must survive, no matter the cost.”  
          “People fear what they don’t understand.”  
          “Monsters are not the only enemies – hunters can be, too.”  
          “Courage isn’t the absence of fear, but acting despite it.”  
          “Even a single step can change your life.”  
          “Those who are prepared never die.”  
          “The unknown is always terrifying.”  
          “There are two types of people in this world: the hunters, and the hunted.”  
          “If you make up your mind, the world will follow.”  
          “Every wound is proof that I’m still alive.”  
          “Everyone wants power, but not everyone is prepared to pay the price.”  
          “To survive, you must be willing to abandon your old self.”  
          “Not everyone who fights monsters becomes a hero.”  
          “No one is born strong – we become strong.”  
          “You don’t need a reason to save someone.”  
          “It’s not over until I give up.”  
          “I stood up because I was sick of kneeling.”  
          “The world changes with or without your consent.”  
          “Sacrifice is not always glorious.”  
          “Some doors can never be closed once opened.”  
          “Even if you kneel, they won’t spare you.”  
          “Who’s the real monster here?”  
          “No one’s coming to save us. We save ourselves.”  
          “A king does not bow his head.”  
          “When you stare into the abyss, the abyss stares back at you.”  
          “Every death will be paid for.”  
          “Not all heroes wear capes; some wear blood and dirt.”  
          “My name is Sung Jinwoo, and I am not afraid of you.”  
          “Let me show you the difference between us.”  
          “From this moment forward, I am the Shadow Monarch.”  )

          selected_quote=${quotes[$RANDOM % ${#quotes[@]}]}
          echo "QUOTE<<EOF" >> $GITHUB_ENV
          echo "$selected_quote" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/<!-- quote-start -->/,/<!-- quote-end -->/c\
          <!-- quote-start -->\n\
          📜 **Quote of the Moment:** '"$QUOTE"'\n\
          <!-- quote-end -->' README.md

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "🔁 Auto-update quote"
          git push
