name: 🔁 Update Quote of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate random quote
        id: quote
        run: |
          quotes=(
            "Biotech meets bytes – building the future."
            "Code your curiosity. Hack your biology."
            "DNA and data – two languages I speak fluently."
            "From pipettes to Python, I explore both worlds."
            "Think like a molecule. Build like a machine."
            "Science without code is just notes."
            "Curiosity is my constant variable."
          )
          picked="${quotes[$RANDOM % ${#quotes[@]}]}"
          echo "quote=$picked" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          quote="${{ steps.quote.outputs.quote }}"
          awk -v q="$quote" '
            BEGIN {start=0}
            /<!--START_SECTION:random-quote-->/ {print; print q; start=1; next}
            /<!--END_SECTION:random-quote-->/ {start=0}
            !start {print}
          ' README.md > temp_readme.md
          mv temp_readme.md README.md

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "🔁 Update quote of the day"
          git push
