name: 🔁 Update Quote of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate random quote
        id: quote
        run: |
          quotes=(
            "Biotech meets bytes – building the future."
            "Code your curiosity. Hack your biology."
            "DNA and data – two languages I speak fluently."
            "From pipettes to Python, I explore both worlds."
            "Think like a molecule. Build like a machine."
            "Science without code is just notes."
            "Curiosity is my constant variable."
          )
          picked="${quotes[$RANDOM % ${#quotes[@]}]}"
          echo "quote=$picked" >> "$GITHUB_OUTPUT"

      - name: Update README.md  # <--- fixed indent here
        run: |
          quote="${{ steps.quote.outputs.quote }}"
          awk -v q="> 💡 $quote" '
            /<!--START_SECTION:random-quote-->/ {
              print; getline; print q; next
            }
            /<!--END_SECTION:random-quote-->/ {print; next}
            !/<!--START_SECTION:random-quote-->/ && !/<!--END_SECTION:random-quote-->/ {print}
          ' README.md > temp_readme.md
          mv temp_readme.md README.md

      - name: Commit and push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'shamkumar06'
          git config --global user.email 'sham@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "🔁 Update quote of the day" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
