name: 🔁 Update Quote of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate random quote
        run: |
          quotes=(
            "Day 1: Biotech meets bytes – building the future."
            "Day 2: Code your curiosity. Hack your biology."
            "Day 3: DNA and data – two languages I speak fluently."
            "Day 4: From pipettes to Python, I explore both worlds."
            "Day 5: Think like a molecule. Build like a machine."
            "Day 6: Science without code is just notes."
            "Day 7: Curiosity is my constant variable."
            "Day 8: Debugging genomes, one line at a time."
            "Day 9: Ctrl + S before centrifuge spins!"
            "Day 10: Brewing bio-algorithms in digital Petri dishes."
            "Day 11: Scripts in one hand, samples in the other."
            "Day 12: Nature runs on code too—it's called DNA."
            "Day 13: Algorithms are the enzymes of logic."
            "Day 14: From cells to circuits—I'm bridging the gap."
            "Day 15: Data is the new petri dish."
            "Day 16: If life is code, CRISPR is the edit tool."
            "Day 17: Just another day decoding life's blueprint."
            "Day 18: Genomes whisper. I listen in Python."
            "Day 19: Every sample has a story. I automate the plot."
            "Day 20: Flask isn’t just for liquids anymore."
            "Day 21: Machine learning meets molecular mapping."
            "Day 22: I merge commits and cells alike."
            "Day 23: My bench has sensors. My scripts have logic."
            "Day 24: Wet lab, dry code—my hybrid zone."
            "Day 25: Science scales better with scripts."
            "Day 26: Data > Gut Feeling. Always."
            "Day 27: I see life in base pairs and binary."
            "Day 28: Innovate like a hacker. Solve like a scientist."
            "Day 29: Real-time PCR meets real-time data."
            "Day 30: Bio-revolution? Already in beta!"
            "Day 31: Code till the cells respond."
            "Day 32: IDEs and incubators run my workflow."
            "Day 33: Open-source science = Open minds."
            "Day 34: AI + DNA = Evolution²"
            "Day 35: A pipette in one hand, logic tree in the other."
            "Day 36: CRON jobs and colony counts, both matter."
            "Day 37: I pipette with precision and program with purpose."
            "Day 38: Automation isn’t the future—it’s my protocol."
            "Day 39: Systems biology, meet system scripts."
            "Day 40: Every failure is just version 0.1."
            "Day 41: Datasets are my lab rats."
            "Day 42: Biological noise? I filter it out in code."
            "Day 43: I brew media and debug memory."
            "Day 44: Biology was cool. I just made it programmable."
            "Day 45: Simulating survival, digitally."
            "Day 46: Not just growth curves—predictive analytics!"
            "Day 47: My experiments loop with logic."
            "Day 48: If it moves, track it. If it grows, model it."
            "Day 49: I believe in intelligent design—machine learning style."
            "Day 50: Living systems, now version-controlled."
          )
          picked="${quotes[$RANDOM % ${#quotes[@]}]}"
          echo "QUOTE=$picked" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          awk -v q="> 💡 ${{ env.QUOTE }}" '
            /<!--START_SECTION:random-quote-->/ {
              print; getline; print q; next
            }
            /<!--END_SECTION:random-quote-->/ {print; next}
            !/<!--START_SECTION:random-quote-->/ && !/<!--END_SECTION:random-quote-->/ {print}
          ' README.md > temp_readme.md
          mv temp_readme.md README.md

      - name: Commit and push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'shamkumar06'
          git config --global user.email 'sham@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "🔁 Update quote of the day" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
